# Generated by Django 3.0.3 on 2020-03-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phnumber', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LearntModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learntmsg', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SeoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_tag', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SkillModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('python', models.CharField(max_length=3)),
                ('django', models.CharField(max_length=3)),
                ('html', models.CharField(max_length=3)),
                ('css', models.CharField(max_length=3)),
                ('scss', models.CharField(max_length=3)),
                ('javascript', models.CharField(max_length=3)),
                ('photoshop', models.CharField(max_length=3)),
                ('illustrator', models.CharField(max_length=3)),
                ('mobilescreen', models.CharField(max_length=100000)),
                ('webscreen', models.CharField(max_length=1000000)),
            ],
        ),
    ]
