# Generated by Django 3.0.3 on 2020-05-04 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactModel',
        ),
    ]
