# Generated by Django 3.2.5 on 2021-09-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_socialmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='linkedin',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
